export { default as ConfirmEmail } from './ConfirmEmail.vue'
export { default as Login } from './Login.vue'
export { default as ResetPassword } from './ResetPassword.vue'
export { default as SignUp } from './SignUp.vue'
export { default as ForgotPassword } from './ForgotPassword.vue'
