FROM debian:bookworm-slim AS base
WORKDIR /usr/src/backend/api-test-helper

ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-static /tini
RUN chmod +x /tini

FROM base AS dev

RUN apt-get update -yq \
    && apt-get install -yq \
      pkg-config \
      openssl \
      libssl-dev \
      curl \
      procps \
      inotify-tools

COPY ./backend/api-test-helper/Cargo.* ./
COPY ./backend/api-test-helper/src ./src/
COPY ./backend/*.sh ../
RUN ../limit-workspace.sh ../Cargo.toml api-test-helper lib-api
COPY ./backend/lib-api ../lib-api/
COPY ./backend/lib-types ../lib-types/
COPY ./backend/db-app ../db-app/

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL
ARG API_TEST_HELPER_HOST
ENV API_TEST_HELPER_HOST=$API_TEST_HELPER_HOST
ARG API_TEST_HELPER_PORT
ENV API_TEST_HELPER_PORT=$API_TEST_HELPER_PORT
ARG APP_AUTH_SECRET
ENV APP_AUTH_SECRET=$APP_AUTH_SECRET

COPY ./backend/target/aarch64-unknown-linux-gnu/debug/libapi_test_helper.* ../target/aarch64-unknown-linux-gnu/debug/
COPY ./backend/target/aarch64-unknown-linux-gnu/debug/api-test-helper* ../target/aarch64-unknown-linux-gnu/debug/

ENTRYPOINT ["/tini", "--"]
CMD ["../run-docker.sh", "api-test-helper"]
