apiVersion: v1
kind: ConfigMap
metadata:
  name: samaquiz-api-config
  labels:
    tier: backend
data:
  LAST_COMMIT_SHA: 'a1234b45'
  RELEASE_VERSION: '1.0-ci'
  EXEC_ENV: ci
  DB_NAME: db_app
  APP_API_HOST: '0.0.0.0'
  APP_API_PORT: '3000'
  APP_API_CORS: "\
    http://localhost:8080,\
    http://localhost:8081,\
    http://localhost:8090,\
    http://localhost:8091,\
    http://127.0.0.1:8080,\
    http://127.0.0.1:8081,\
    http://127.0.0.1:8090,\
    http://127.0.0.1:8091,\
    http://web.localhost:8080"
  APP_WEB_URL: 'http://localhost:8080'
  S3_URL: https://da7c8f85bc450afcae564b1d7ae16d4e.r2.cloudflarestorage.com
  S3_ACCESS_KEY_ID: ci
  CONFIRM_SHARED_SECRET: '9V+nTEFjyHimQBAHqseuB3+VKnvJ/YRZnHOVo8ytAHU='
  APP_AUTH_SECRET: 'hj+7Dvc5QxP6nLCO814q1FuLDpMgg7sAe79cieSMIqs='
