apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: samaquiz-api
requires:
  - path: ./skaffold.db.yaml
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
    - image: samaquiz-api.dev
      context: ../
      sync:
        manual:
          - src: 'backend/samaquiz-api/src/**/*'
            dest: '/usr/src'
          # Copy shared libs
          - src: 'backend/lib-api/src/**/*'
            dest: '/usr/src'
          - src: 'backend/lib-types/src/**/*'
            dest: '/usr/src'
          # Copy pre-built app binaries
          - src: 'backend/target/aarch64-unknown-linux-gnu/debug/samaquiz-api*'
            dest: '/usr/src'
          - src: 'backend/target/aarch64-unknown-linux-gnu/debug/libsamaquiz_api.*'
            dest: '/usr/src'
      docker:
        dockerfile: backend/samaquiz-api/Dockerfile.dev
        target: dev
        buildArgs:
          # These vars can be overridden in order to manually test stg/prod environments
          S3_SECRET_ACCESS_KEY: '{{or .S3_SECRET_ACCESS_KEY "dev"}}'
          S3_ACCESS_KEY_ID: '{{or .S3_ACCESS_KEY_ID "dev"}}'
          SENDGRID_API_KEY: '{{or .SENDGRID_API_KEY "dev"}}'
          APP_AUTH_SECRET: '{{or .APP_AUTH_SECRET "dev"}}'
    - image: api-test-helper.dev
      context: ../
      sync:
        manual:
          - src: 'backend/api-test-helper/src/**/*'
            dest: '/usr/src'
          - src: 'backend/lib-api/src/**/*'
            dest: '/usr/src'
          - src: 'backend/lib-types/src/**/*'
            dest: '/usr/src'
          - src: 'backend/db-app/src/**/*'
            dest: '/usr/src'
          - src: 'backend/target/aarch64-unknown-linux-gnu/debug/api-test-helper*'
            dest: '/usr/src'
          - src: 'backend/target/aarch64-unknown-linux-gnu/debug/libapi_test_helper.*'
            dest: '/usr/src'
      docker:
        dockerfile: backend/api-test-helper/Dockerfile.dev
        target: dev
        buildArgs:
          APP_AUTH_SECRET: '{{or .APP_AUTH_SECRET}}'

manifests:
  rawYaml:
    - k8s/dev/shared/*.yaml
    - k8s/dev/api/*.yaml

deploy:
  # kubeContext: rancher-desktop
  kubeContext: docker-desktop
  kubectl: {}
portForward:
  # Expose API for local E2E run
  - resourceType: service
    resourceName: samaquiz-api
    port: 3000
  # Expose state manager app localhost connection
  - resourceType: service
    resourceName: api-test-helper
    port: 3001
